DROP TABLE IF EXISTS PERSON;
  
CREATE TABLE PERSON (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS REGIONS;
  
CREATE TABLE REGIONS (
  region_id NUMBER PRIMARY KEY,
  region_name VARCHAR(25) NOT NULL
);

DROP TABLE IF EXISTS COUNTRIES;

CREATE TABLE COUNTRIES (
  country_id CHAR(2) PRIMARY KEY,
  country_name VARCHAR2(40),
  region_region_id NUMBER
);

DROP TABLE IF EXISTS LOCATIONS;

CREATE TABLE LOCATIONS (
  location_id NUMBER PRIMARY KEY,
  street_address VARCHAR2(40),
  postal_code VARCHAR2(12),
  city VARCHAR2(30) NOT NULL,
  state_province VARCHAR2(25),
  country_country_id CHAR(2)
);
